title: My Blog
author: Yu
description: 以自律为路-以钻研为灯-成就自我
footer_desc: >-
  <br>
  © 2024-- **** <br>

url: 
baseurl: 
disqus: 
ga4: 

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      comments: true
      toc: true
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      comments: false

show_excerpts: true
locale: zh-Hans
lang: zh-Hans
date_format: "%Y-%m-%d"
timezone: Asia/Shanghai
# timezone: Europe/Amsterdam
permalink: /posts/:title
plugins:
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-sitemap

feed:
  posts_limit: 20
  excerpt_only: true
  excerpt_tip: "记录自己学习的过程"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - vercel.json
